name: u
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.12.12=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.12=h7f8727e_0
  - pip=23.3.1=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - cachetools==5.3.2
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - editdistance==0.6.2
      - einops==0.7.0
      - filelock==3.13.1
      - fonttools==4.47.2
      - fsspec==2023.12.2
      - google-auth==2.27.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.60.0
      - huggingface-hub==0.20.3
      - idna==3.6
      - imageio==2.33.1
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.1
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - markdown==3.5.2
      - markupsafe==2.1.4
      - matplotlib==3.7.4
      - networkx==3.1
      - numpy==1.24.4
      - oauthlib==3.2.2
      - opencv-python==4.9.0.80
      - packaging==23.2
      - pandas==2.0.3
      - pillow==10.2.0
      - protobuf==4.25.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.4
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - safetensors==0.4.2
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - six==1.16.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.2.0
      - tifffile==2023.7.10
      - timm==0.9.12
      - torch==1.13.0+cu117
      - torchaudio==0.13.0+cu117
      - torchvision==0.14.0+cu117
      - tqdm==4.66.1
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - urllib3==2.1.0
      - werkzeug==3.0.1
      - zipp==3.17.0
prefix: /home/liyuting/miniconda3/envs/u
